name: CD

on:
  push:
    branches: [ principal ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Simulate deploy
        run: echo "Deploy simulado com sucesso!"
