name: CI

on:
  push:
    branches: [ principal, dev ]
  pull_request:
    branches: [ principal, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List project files
        run: ls -R
